export const todoTypes = {
  FETCH_TODO: "FETCH_TODO",
  FETCH_TODO_START: "FETCH_TODO_START",
  FETCH_TODO_SUCCESS: "FETCH_TODO_SUCCESS",
  FETCH_TODO_FAILED: "FETCH_TODO_FAILED",
  CHECK_TODO: "CHECK_TODO",
  UPDATE_FILTERED_TODO_LIST: "UPDATE_FILTERED_TODO_LIST",
} as const;
